In [28]:
file_path = "story.txt"

# Open the file for reading
try:
    with open(file_path, "r") as file:
        text = file.read()  # Read the entire contents of the file
        print(text)  # Print the story to the console
except FileNotFoundError:
    print(f"The file '{file_path}' was not found.")
except Exception as e:
    print(f"An error occurred: {e}")


In a groundbreaking achievement for the renewable energy sector, scientists and engineers have announced a significant breakthrough in solar panel technology, resulting in record breaking levels of efficiency. This development marks a pivotal moment in the global pursuit of sustainable and clean energy sources.

For years, the solar energy industry has been striving to enhance the efficiency of solar panels, with the aim of capturing and converting more sunlight into electricity. Traditional photovoltaic cells have long been limited by their ability to harness a fraction of the available solar energy. However, recent innovations have pushed the boundaries of what was once thought possible.

The research team, led by Dr. Sarah Mitchell at the Green Energy Institute, has managed to achieve a stunning 50% increase in the efficiency of solar panels. This means that the new generation of solar panels can convert half of the incoming sunlight into electricity, compared to the previous indus

In [29]:
import string

temp_text = ""
for letter in text:
    if letter not in string.punctuation:
        temp_text += letter
text = temp_text
print(text)


In a groundbreaking achievement for the renewable energy sector scientists and engineers have announced a significant breakthrough in solar panel technology resulting in record breaking levels of efficiency This development marks a pivotal moment in the global pursuit of sustainable and clean energy sources

For years the solar energy industry has been striving to enhance the efficiency of solar panels with the aim of capturing and converting more sunlight into electricity Traditional photovoltaic cells have long been limited by their ability to harness a fraction of the available solar energy However recent innovations have pushed the boundaries of what was once thought possible

The research team led by Dr Sarah Mitchell at the Green Energy Institute has managed to achieve a stunning 50 increase in the efficiency of solar panels This means that the new generation of solar panels can convert half of the incoming sunlight into electricity compared to the previous industry standard of 

In [30]:
# tokenize the text
import nltk
import string

nltk.download("punkt")  # Download the tokenizer data (if not already downloaded)
tokenized_text = nltk.word_tokenize(text)

print(tokenized_text)

['In', 'a', 'groundbreaking', 'achievement', 'for', 'the', 'renewable', 'energy', 'sector', 'scientists', 'and', 'engineers', 'have', 'announced', 'a', 'significant', 'breakthrough', 'in', 'solar', 'panel', 'technology', 'resulting', 'in', 'record', 'breaking', 'levels', 'of', 'efficiency', 'This', 'development', 'marks', 'a', 'pivotal', 'moment', 'in', 'the', 'global', 'pursuit', 'of', 'sustainable', 'and', 'clean', 'energy', 'sources', 'For', 'years', 'the', 'solar', 'energy', 'industry', 'has', 'been', 'striving', 'to', 'enhance', 'the', 'efficiency', 'of', 'solar', 'panels', 'with', 'the', 'aim', 'of', 'capturing', 'and', 'converting', 'more', 'sunlight', 'into', 'electricity', 'Traditional', 'photovoltaic', 'cells', 'have', 'long', 'been', 'limited', 'by', 'their', 'ability', 'to', 'harness', 'a', 'fraction', 'of', 'the', 'available', 'solar', 'energy', 'However', 'recent', 'innovations', 'have', 'pushed', 'the', 'boundaries', 'of', 'what', 'was', 'once', 'thought', 'possible', 'T

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Saad\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [31]:
# mapping each unique word to an index
vocabulary_index = {}
index_vocabulary = {}
i = 0
for word in tokenized_text:
    if word not in vocabulary_index:
        vocabulary_index[word] = i
        index_vocabulary[i] = word
        i += 1
vocabulary_size = len(vocabulary_index)

print(vocabulary_index)
print(vocabulary_size)

{'In': 0, 'a': 1, 'groundbreaking': 2, 'achievement': 3, 'for': 4, 'the': 5, 'renewable': 6, 'energy': 7, 'sector': 8, 'scientists': 9, 'and': 10, 'engineers': 11, 'have': 12, 'announced': 13, 'significant': 14, 'breakthrough': 15, 'in': 16, 'solar': 17, 'panel': 18, 'technology': 19, 'resulting': 20, 'record': 21, 'breaking': 22, 'levels': 23, 'of': 24, 'efficiency': 25, 'This': 26, 'development': 27, 'marks': 28, 'pivotal': 29, 'moment': 30, 'global': 31, 'pursuit': 32, 'sustainable': 33, 'clean': 34, 'sources': 35, 'For': 36, 'years': 37, 'industry': 38, 'has': 39, 'been': 40, 'striving': 41, 'to': 42, 'enhance': 43, 'panels': 44, 'with': 45, 'aim': 46, 'capturing': 47, 'converting': 48, 'more': 49, 'sunlight': 50, 'into': 51, 'electricity': 52, 'Traditional': 53, 'photovoltaic': 54, 'cells': 55, 'long': 56, 'limited': 57, 'by': 58, 'their': 59, 'ability': 60, 'harness': 61, 'fraction': 62, 'available': 63, 'However': 64, 'recent': 65, 'innovations': 66, 'pushed': 67, 'boundaries': 

In [32]:
n = 4  # the value of n in n-gram

In [33]:
# generate ngrams
from nltk.util import ngrams
import numpy as np

ngrams = np.array(list((ngrams(tokenized_text, n))))

# Print the ngrams
print(ngrams)

print(ngrams.shape)

[['In' 'a' 'groundbreaking' 'achievement']
 ['a' 'groundbreaking' 'achievement' 'for']
 ['groundbreaking' 'achievement' 'for' 'the']
 ...
 ['can' 'continue' 'to' 'grow']
 ['continue' 'to' 'grow' 'and']
 ['to' 'grow' 'and' 'evolve']]
(3838, 4)


In [34]:
from gensim.models import KeyedVectors

# Path to the downloaded Word2Vec binary file
model_path = "D:\deep learning\GoogleNews-vectors-negative300.bin.gz"

# Load the Word2Vec model
word2vec_model = KeyedVectors.load_word2vec_format(model_path, binary=True)

In [35]:
# Test the loaded model
similar_words = word2vec_model.most_similar("king")
print("Words most similar to 'king':")
for word, score in similar_words:
    print(f"{word}: {score}")

Words most similar to 'king':
kings: 0.7138045430183411
queen: 0.6510956883430481
monarch: 0.6413194537162781
crown_prince: 0.6204220056533813
prince: 0.6159993410110474
sultan: 0.5864824056625366
ruler: 0.5797567367553711
princes: 0.5646552443504333
Prince_Paras: 0.5432944297790527
throne: 0.5422105193138123


In [36]:
import numpy as np

# separate into x-set and y-set. The x-set will contain word embeddings of first n-1 words of each ngram. The y-set will contain the
# one-hot encodings of the last word of each ngram
x = []
y = []
for ngram in ngrams:
    single_example = []
    for i in range(n - 1):
        if word2vec_model.__contains__(ngram[i]):
            single_example.append(word2vec_model[ngram[i]].flatten())
        # elif ngram[i] == ".":
        #     single_example.insert(1, [0 for j in range(300)])
        else:
            single_example.insert(0, [0 for j in range(300)])

    y.append(
        vocabulary_index[ngram[n - 1]]
    )  # convert word to its corresponding integer as defined by vocabulary_index
    x.append(single_example)

x = np.array(x)  # convert x into numpy array

# convert each integer in y to one-hot encoding
y = np.eye(vocabulary_size)[y]

print(x.shape)
print(y.shape)

(3838, 3, 300)
(3838, 1108)


In [37]:
print(x)

[[[ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 0.03222656  0.12207031  0.22558594 ...  0.04931641 -0.05175781
   -0.12451172]
  [-0.16113281  0.0050354   0.08886719 ...  0.10302734 -0.03198242
   -0.02124023]]

 [[ 0.          0.          0.         ...  0.          0.
    0.        ]
  [-0.16113281  0.0050354   0.08886719 ...  0.10302734 -0.03198242
   -0.02124023]
  [-0.15625     0.01489258  0.17675781 ...  0.29296875 -0.00081253
   -0.11328125]]

 [[-0.16113281  0.0050354   0.08886719 ...  0.10302734 -0.03198242
   -0.02124023]
  [-0.15625     0.01489258  0.17675781 ...  0.29296875 -0.00081253
   -0.11328125]
  [-0.01177979 -0.04736328  0.04467773 ...  0.07128906 -0.03491211
    0.02416992]]

 ...

 [[ 0.          0.          0.         ...  0.          0.
    0.        ]
  [ 0.09765625 -0.03564453  0.09179688 ... -0.19335938 -0.11767578
    0.05078125]
  [-0.04467773  0.11328125 -0.10400391 ...  0.08300781  0.17382812
   -0.13085938]]

 [[ 0.        

In [38]:
print(y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [39]:
from keras.models import Sequential
from keras.layers import LSTM, Bidirectional, Dense, Input
from keras.initializers import RandomUniform


model = Sequential(
    [
        Input(shape=(x.shape[1], x.shape[2])),
        Bidirectional(LSTM(units=10, activation="linear")),
        Dense(
            units=vocabulary_size,
            kernel_initializer=RandomUniform(minval=-1, maxval=1),
            activation="softmax",
        ),
    ]
)

model.compile(loss="categorical_crossentropy", optimizer="adam")

In [40]:
model.fit(x, y, batch_size=32, epochs=100)

Epoch 1/100
120/120 [==============================] - 3s 4ms/step - loss: 6.9545
Epoch 2/100
120/120 [==============================] - 0s 4ms/step - loss: 6.6668
Epoch 3/100
120/120 [==============================] - 1s 5ms/step - loss: 6.2440
Epoch 4/100
120/120 [==============================] - 1s 4ms/step - loss: 5.9692
Epoch 5/100
120/120 [==============================] - 1s 4ms/step - loss: 5.7907
Epoch 6/100
120/120 [==============================] - 0s 4ms/step - loss: 5.6487
Epoch 7/100
120/120 [==============================] - 0s 4ms/step - loss: 5.5249
Epoch 8/100
120/120 [==============================] - 1s 4ms/step - loss: 5.4102
Epoch 9/100
120/120 [==============================] - 1s 4ms/step - loss: 5.3075
Epoch 10/100
120/120 [==============================] - 1s 4ms/step - loss: 5.2063
Epoch 11/100
120/120 [==============================] - 1s 5ms/step - loss: 5.1042
Epoch 12/100
120/120 [==============================] - 1s 5ms/step - loss: 5.0101
Epoch 13/100


In [41]:
def predict_next_word(partial_sentence):
    tokens = partial_sentence.split(" ")
    x = []
    for i in range(len(tokens) - n + 1, len(tokens)):
        if word2vec_model.__contains__(tokens[i]):
            x.append(word2vec_model[tokens[i]].flatten())
        else:
            x.append([0 for j in range(300)])

    x = np.expand_dims(x, axis=0)

    prediction = model.predict(x)
    return index_vocabulary[np.argmax(prediction)]


print(predict_next_word("you can"))

1/1 [==============================] - 0s 388ms/step
try


In [44]:
def generate_sentence(seed, number_of_words_to_generate):
    sentence = seed
    for i in range(number_of_words_to_generate):
        next_word = predict_next_word(sentence)
        sentence = sentence + " " + next_word
    return sentence


print(
    generate_sentence(
        "the last thing",
        number_of_words_to_generate=10,
    )
)

1/1 [==============================] - 0s 21ms/step
the last thing except this is a a more efficient flow of these
